version: '3.8'

services:
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/resources:/var/www/resources
  #     - ./nginx/log:/var/log/nginx/enc
  #   environment:
  #     - ENCRYPTION_PASSWORD=${ENCRYPTION_PASSWORD}
  #   depends_on:
  #     - webshop_service
  #   networks:
  #     - shared_network


  psql_webshop:
    image: postgres:15-bookworm
    environment:
      POSTGRES_DB: ${WEBSHOP_DB_DATABASE}
      POSTGRES_USER: ${WEBSHOP_DB_USERNAME}
      POSTGRES_PASSWORD: ${WEBSHOP_DB_PASSWORD}
    ports:
      - "${WEBSHOP_DB_PORT}:5432"
    volumes:
      - pgdata_webshop:/var/lib/postgresql/data
    networks:
      - webshop_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${WEBSHOP_DB_USERNAME} -d ${WEBSHOP_DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  webshop_service:
    build:
      context: ./webshop
      dockerfile: Dockerfile
    environment:
      PORT: ${WEBSHOP_PORT}
      DB_HOST_PORT: ${DB_HOST_PORT}
      APP_ENV: ${WEBSHOP_APP_ENV}
      DB_PORT: ${WEBSHOP_DB_PORT}
      DB_HOST: ${WEBSHOP_DB_HOST}
      DB_DATABASE: ${WEBSHOP_DB_DATABASE}
      DB_USERNAME: ${WEBSHOP_DB_USERNAME}
      DB_PASSWORD: ${WEBSHOP_DB_PASSWORD}
      DB_SCHEMA: ${WEBSHOP_DB_SCHEMA}
    # deploy:
    #   replicas: 3
    # ports:
    #   - "8080-8082:8080"
    ports:
      - "8080:8080"
    depends_on:
      psql_webshop:
        condition: service_healthy
    networks:
      - webshop_network
      - shared_network

networks:
  shared_network:
    driver: bridge
  webshop_network:
    driver: bridge

volumes:
    pgdata_webshop:
